version: "3.7"

services:
    ts_food_market:
        container_name: shinsegae
        platform: linux/amd64
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ".t:/app"
            - "/app/node_modules"
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
